name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    name: Release assets
    runs-on: ${{ matrix.config.os }}
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.REPO_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.REPO_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-2
      AWS_DEFAULT_OUTPUT: json
    strategy:
      fail-fast: false
      matrix:
        config:
          # Linux
          - {os: ubuntu-latest, toolchain: stable, target: x86_64-unknown-linux-gnu, cross: false}
          - {os: ubuntu-latest, toolchain: stable, target: aarch64-unknown-linux-gnu, cross: true}
          # Macos
          - {os: macos-11, toolchain: stable, target: x86_64-apple-darwin, cross: false}
          - {os: macos-11, toolchain: stable, target: aarch64-apple-darwin, cross: false}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Node.js setup
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Build front-end dist
        run:
          npm install
          npm run build

      - name: Rust setup
        run: |
          bash ./scripts/setup/dev_setup.sh
          cargo install --version 0.1.16 cross
      - name: Build Binary
        run: |
          if [ ${{ matrix.config.os }} = "macos-11" ]; then
              rustup target add aarch64-apple-darwin
          fi
          if [ ${{ matrix.config.cross }} = true ]; then
              cross build --release --target=${{ matrix.config.target }}
          else
              cargo build --release --target=${{ matrix.config.target }}
          fi
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Pack binaries
        run: |
          if [ ${{ matrix.config.os }} = "macos-11" ]; then
            brew install gnu-tar
            sudo /usr/sbin/purge
            gtar -C ./target/${{ matrix.config.target }}/release -czvf databend-playground-${{ steps.get_version.outputs.VERSION }}-${{ matrix.config.target }}.tar.gz databend-playground
          else
            tar -C ./target/${{ matrix.config.target }}/release -czvf databend-playground-${{ steps.get_version.outputs.VERSION }}-${{ matrix.config.target }}.tar.gz databend-playground
          fi

      - name: Release databend-playground
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: databend-playground-${{ steps.get_version.outputs.VERSION }}-${{ matrix.config.target }}.*
          asset_name: databend-playground-${{ steps.get_version.outputs.VERSION }}-${{ matrix.config.target }}
          tag: ${{ github.ref }}
          file_glob: true
          overwrite: true
          body: ${{ steps.changelog_reader.outputs.log_entry }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.REPO_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.REPO_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Sync release to S3
        run: |
          aws s3 cp databend-playground-${{ steps.get_version.outputs.VERSION }}-${{ matrix.config.target }}.tar.gz s3://repo.databend.rs/databend/${{ steps.get_version.outputs.VERSION }}/databend-playground-${{ steps.get_version.outputs.VERSION }}-${{ matrix.config.target }}.tar.gz
